name: "Branch Protection Rules"
target: branch
enforcement: active

conditions:
  ref_name:
    include:
      - "refs/heads/main"
    exclude: []

rules:
  # Require pull request before merging
  - type: pull_request
    parameters:
      required_approving_review_count: 1
      dismiss_stale_reviews_on_push: true
      require_code_owner_review: false
      require_last_push_approval: false
      required_review_thread_resolution: true

  # Require status checks to pass
  - type: required_status_checks
    parameters:
      strict_required_status_checks_policy: true
      required_status_checks:
        - context: "Lint"
        - context: "Build"

  # Prevent force pushes
  - type: non_fast_forward

  # Prevent deletion of the branch
  - type: deletion

  # Require signed commits (optional - can be enabled for extra security)
  # - type: required_signatures

bypass_actors:
  # Repository administrators can bypass these rules
  # Note: actor_id 5 represents the "Admin" role in GitHub's repository role system
  # Role IDs: 1=Read, 2=Triage, 4=Write, 5=Maintain, 6=Admin
  - actor_id: 5
    actor_type: RepositoryRole
    bypass_mode: always
